---
clusters:
  - name: Stream Processing Cluster
    services: [CRUISE_CONTROL, HDFS, INFRA_SOLR, KAFKA, RANGER, SCHEMAREGISTRY, STREAMS_MESSAGING_MANAGER, ZOOKEEPER]
    repositories:
      - https://archive.cloudera.com/p/cdh7/7.1.3.0/parcels/
    security:
      kerberos: true
      tls: true
    configs:
      HDFS:
        DATANODE:
          dfs_data_dir_list: /dfs/dn
        NAMENODE:
          dfs_name_dir_list: /dfs/nn
        SECONDARYNAMENODE:
          fs_checkpoint_dir_list: /dfs/snn
      ZOOKEEPER:
        SERVICEWIDE:
          zookeeper_datadir_autocreate: true
    host_templates:
      Master1:
        CRUISE_CONTROL: [CRUISE_CONTROL_SERVER]
        HDFS: [NAMENODE, SECONDARYNAMENODE]
        INFRA_SOLR: [SOLR_SERVER]
        RANGER: [RANGER_ADMIN, RANGER_TAGSYNC, RANGER_USERSYNC]
        SCHEMAREGISTRY: [SCHEMA_REGISTRY_SERVER]
        STREAMS_MESSAGING_MANAGER: [STREAMS_MESSAGING_MANAGER_UI, STREAMS_MESSAGING_MANAGER_SERVER]
        ZOOKEEPER: [SERVER]
      Workers:
        HDFS: [DATANODE]
        KAFKA: [KAFKA_BROKER]
        SCHEMAREGISTRY: [GATEWAY]

mgmt:
  name: Cloudera Management Service
  services: [ALERTPUBLISHER, EVENTSERVER, HOSTMONITOR, REPORTSMANAGER, SERVICEMONITOR]
  security:
    tls: true

hosts:
  configs:
    host_default_proc_memswap_thresholds:
      warning: never
      critical: never
    host_memswap_thresholds:
      warning: never
      critical: never
    host_config_suppression_agent_system_user_group_validator: true
