---
clusters:
  - name: Flow Management Cluster
    services: [HDFS, NIFI, NIFIREGISTRY, ZOOKEEPER]
    security:
      kerberos: true
    repositories:
      - https://archive.cloudera.com/p/cdh7/7.1.3.0/parcels/
      - https://archive.cloudera.com/p/CFM/centos7/2.x/updates/2.0.1.0/tars/parcel/
    configs:
      HDFS:
        SERVICEWIDE:
          hdfs_verify_ec_with_topology_enabled: false
        DATANODE:
          dfs_data_dir_list: /dfs/dn
        NAMENODE:
          dfs_name_dir_list: /dfs/nn
        SECONDARYNAMENODE:
          fs_checkpoint_dir_list: /dfs/snn
      ZOOKEEPER:
        SERVICEWIDE:
          zookeeper_datadir_autocreate: true
    host_templates:
      Master1:
        HDFS: [NAMENODE, SECONDARYNAMENODE]
        NIFIREGISTRY: [NIFI_REGISTRY_SERVER, GATEWAY]
      Workers:
        HDFS: [DATANODE]
        NIFI: [NIFI_NODE, GATEWAY]
        ZOOKEEPER: [SERVER]

mgmt:
  name: Cloudera Management Service
  services: [ALERTPUBLISHER, EVENTSERVER, HOSTMONITOR, REPORTSMANAGER, SERVICEMONITOR]

hosts:
  configs:
    host_default_proc_memswap_thresholds:
      warning: never
      critical: never
    host_memswap_thresholds:
      warning: never
      critical: never
    host_config_suppression_agent_system_user_group_validator: true
