---
cluster_definition: definitions/7.1.x/flow-management
cloudera_manager_version: 7.1.3
cloudera_manager_repo_username: "{{ vault__cloudera_manager_repo_username }}"
cloudera_manager_repo_password: "{{ vault__cloudera_manager_repo_password }}"
cloudera_manager_license_type: enterprise
cloudera_manager_license_file: testing/license.txt
cloudera_manager_csds:
  - https://archive.cloudera.com/p/CFM/centos7/2.x/updates/2.0.1.0/tars/parcel/NIFI-1.11.4.2.0.1.0-71.jar
  - https://archive.cloudera.com/p/CFM/centos7/2.x/updates/2.0.1.0/tars/parcel/NIFIREGISTRY-0.6.0.2.0.1.0-71.jar

cloudera_manager_options:
  CUSTOM_BANNER_HTML: "Cloudera Ansible Playbook v2 - {{ cluster_definition }}"

database_type: postgresql
database_version: 10
