---
cluster_definition: definitions/7.1.x/spark3
cloudera_manager_version: 7.1.3
cloudera_manager_repo_username: "{{ vault__cloudera_manager_repo_username }}"
cloudera_manager_repo_password: "{{ vault__cloudera_manager_repo_password }}"
cloudera_manager_license_type: enterprise
cloudera_manager_license_file: testing/license.txt
cloudera_manager_options:
  CUSTOM_BANNER_HTML: "Cloudera Ansible Playbook v2 - {{ cluster_definition }}"
cloudera_manager_csds:
  - https://archive.cloudera.com/p/spark3/2.99.7110.0/csd/SPARK3_ON_YARN-3.0.0.2.99.7110.0-18.jar
