---
clusters:
  - name: Accumulo Cluster
    services: [ACCUMULO16, HDFS, HIVE, HUE, IMPALA, OOZIE, SPARK_ON_YARN, SPARK2_ON_YARN, YARN, ZOOKEEPER]
    repositories:
      - https://archive.cloudera.com/cdh5/parcels/5.16.2/
      - https://archive.cloudera.com/spark2/parcels/2.4.0.cloudera2/
      - https://archive.cloudera.com/accumulo-c5/parcels/1.7.2/
    configs:
      HDFS:
        DATANODE:
          dfs_data_dir_list: /dfs/dn
          dfs_datanode_failed_volumes_tolerated: 0
          dfs_datanode_max_locked_memory: 0
        NAMENODE:
          dfs_name_dir_list: /dfs/nn
        SECONDARYNAMENODE:
          fs_checkpoint_dir_list: /dfs/snn
      IMPALA:
        IMPALAD:
          scratch_dirs: /tmp/impala
      YARN:
        RESOURCEMANAGER:
          yarn_scheduler_maximum_allocation_mb: 4096
          yarn_scheduler_maximum_allocation_vcores: 4
        NODEMANAGER:
          yarn_nodemanager_resource_memory_mb: 4096
          yarn_nodemanager_resource_cpu_vcores: 4
          yarn_nodemanager_local_dirs:  /tmp/nm
          yarn_nodemanager_log_dirs: /var/log/nm
        GATEWAY:
          mapred_submit_replication: 3
          mapred_reduce_tasks: 6
      ZOOKEEPER:
        SERVICEWIDE:
          zookeeper_datadir_autocreate: true
    host_templates:
      Master1:
        ACCUMULO16: [ACCUMULO16_GC, ACCUMULO16_MASTER, ACCUMULO16_MONITOR, ACCUMULO16_TRACER]
        HDFS: [NAMENODE, SECONDARYNAMENODE]
        HIVE: [HIVEMETASTORE, HIVESERVER2, GATEWAY]
        HUE: [HUE_SERVER, HUE_LOAD_BALANCER]
        IMPALA: [STATESTORE, CATALOGSERVER]
        OOZIE: [OOZIE_SERVER]
        SPARK_ON_YARN: [SPARK_YARN_HISTORY_SERVER]
        SPARK2_ON_YARN: [SPARK2_YARN_HISTORY_SERVER]
        YARN: [RESOURCEMANAGER, JOBHISTORY]
        ZOOKEEPER: [SERVER]
      Workers:
        ACCUMULO16: [ACCUMULO16_TSERVER]
        HDFS: [DATANODE]
        HIVE: [GATEWAY]
        IMPALA: [IMPALAD]
        SPARK_ON_YARN: [GATEWAY]
        SPARK2_ON_YARN: [GATEWAY]
        YARN: [NODEMANAGER]

mgmt:
  name: Cloudera Management Service
  services: [ALERTPUBLISHER, EVENTSERVER, HOSTMONITOR, NAVIGATOR, NAVIGATORMETASERVER, REPORTSMANAGER, SERVICEMONITOR]

hosts:
  configs:
    host_memswap_thresholds:
      warning: never
      critical: never
