---
clusters:
  - name: Streaming Analytics Cluster
    services: [HBASE, HDFS, FLINK, INFRA_SOLR, KAFKA, QUEUEMANAGER, RANGER, SPARK_ON_YARN, YARN, ZOOKEEPER]
    security:
      kerberos: true
    repositories:
      - https://archive.cloudera.com/p/cdh7/7.1.3.0/parcels/
      - https://archive.cloudera.com/p/csa/1.2.0.0/parcels/
    configs:
      FLINK:
        FLINK_HISTORY_SERVER:
          historyserver_web_port: 8182
      HDFS:
        DATANODE:
          dfs_data_dir_list: /dfs/dn
        NAMENODE:
          dfs_name_dir_list: /dfs/nn
        SECONDARYNAMENODE:
          fs_checkpoint_dir_list: /dfs/snn
      ZOOKEEPER:
        SERVICEWIDE:
          zookeeper_datadir_autocreate: true
    host_templates:
      Master1:
        FLINK: [FLINK_HISTORY_SERVER]
        HBASE: [MASTER]
        HDFS: [NAMENODE, SECONDARYNAMENODE]
        INFRA_SOLR: [SOLR_SERVER]
        QUEUEMANAGER: [QUEUEMANAGER_STORE, QUEUEMANAGER_WEBAPP]
        RANGER: [RANGER_ADMIN, RANGER_TAGSYNC, RANGER_USERSYNC]
        SPARK_ON_YARN: [SPARK_YARN_HISTORY_SERVER]
        YARN: [RESOURCEMANAGER, JOBHISTORY]
        ZOOKEEPER: [SERVER]
      Workers:
        FLINK: [GATEWAY]
        HBASE: [REGIONSERVER]
        HDFS: [DATANODE]
        KAFKA: [KAFKA_BROKER]
        SPARK_ON_YARN: [GATEWAY]
        YARN: [NODEMANAGER]

mgmt:
  name: Cloudera Management Service
  services: [ALERTPUBLISHER, EVENTSERVER, HOSTMONITOR, REPORTSMANAGER, SERVICEMONITOR]

hosts:
  configs:
    host_default_proc_memswap_thresholds:
      warning: never
      critical: never
    host_memswap_thresholds:
      warning: never
      critical: never
    host_config_suppression_agent_system_user_group_validator: true
