---
clusters:
  - name: CDP PvC Base Cluster
    services: [HDFS, INFRA_SOLR, RANGER, ZOOKEEPER]
    security:
      kerberos: true
      hdfs_encryption: true
      tls: true
    repositories:
      - https://archive.cloudera.com/p/cdh7/7.1.3.0/parcels/
    configs:
      HDFS:
        SERVICEWIDE:
          hdfs_verify_ec_with_topology_enabled: false
        DATANODE:
          dfs_data_dir_list: /dfs/dn
          dfs_datanode_max_locked_memory: 0
        NAMENODE:
          dfs_name_dir_list: /dfs/nn
        SECONDARYNAMENODE:
          fs_checkpoint_dir_list: /dfs/snn
      ZOOKEEPER:
        SERVICEWIDE:
          zookeeper_datadir_autocreate: true
    host_templates:
      Master:
        HDFS: [NAMENODE, SECONDARYNAMENODE]
        INFRA_SOLR: [SOLR_SERVER]
        RANGER: [RANGER_ADMIN, RANGER_TAGSYNC, RANGER_USERSYNC]
        ZOOKEEPER: [SERVER]
      Workers:
        HDFS: [DATANODE]

  - name: KTS Cluster
    type: kts
    repositories:
      - https://archive.cloudera.com/p/cdh7/7.1.3.0/parcels/
      - http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/3050880/parcels/

mgmt:
  name: Cloudera Management Service
  services: [ALERTPUBLISHER, EVENTSERVER, HOSTMONITOR, REPORTSMANAGER, SERVICEMONITOR]
  security:
    tls: true

hosts:
  configs:
    host_default_proc_memswap_thresholds:
      warning: never
      critical: never
    host_memswap_thresholds:
      warning: never
      critical: never
    host_config_suppression_agent_system_user_group_validator: true
    host_config_suppression_memory_overcommitted_validator: true

