---
cluster_definition: definitions/6.3.x/flow-management
cloudera_manager_version: 6.3.3
cloudera_manager_repo_username: "{{ vault__cloudera_manager_repo_username }}"
cloudera_manager_repo_password: "{{ vault__cloudera_manager_repo_password }}"
cloudera_manager_license_type: enterprise
cloudera_manager_license_file: testing/license.txt
cloudera_manager_csds:
  - https://archive.cloudera.com/p/CFM/centos7/1.x/updates/1.1.0.0/tars/parcel/NIFI-1.11.4.1.1.0.0-119.jar
  - https://archive.cloudera.com/p/CFM/centos7/1.x/updates/1.1.0.0/tars/parcel/NIFICA-1.11.4.1.1.0.0-119.jar
  - https://archive.cloudera.com/p/CFM/centos7/1.x/updates/1.1.0.0/tars/parcel/NIFIREGISTRY-0.6.0.1.1.0.0-119.jar
cloudera_manager_options:
  CUSTOM_BANNER_HTML: "Cloudera Ansible Playbook v2 - {{ cluster_definition }}"

database_type: mariadb
database_version: 10.1
