---
clusters:
  - name: pvc-base
    services: [ATLAS, HBASE, HDFS, HIVE, HIVE_ON_TEZ, INFRA_SOLR, KAFKA, RANGER, QUEUEMANAGER, TEZ, YARN, ZOOKEEPER, OZONE, KNOX]
    repositories:
      - https://archive.cloudera.com/p/cdh7/7.1.3.0/parcels/
    security:
      kerberos: true
    configs:
      HDFS:
        SERVICEWIDE:
          dfs_ha_fencing_methods: 'shell(true)'
          dfs_namenode_acls_enabled: true
          enable_ranger_authorization: true
        DATANODE:
          dfs_data_dir_list: /dfs/dn
        NAMENODE:
          autofailover_enabled: true
          dfs_federation_namenode_nameservice: nameservice1
          dfs_name_dir_list: /dfs/nn
          dfs_namenode_quorum_journal_name: nameservice1
        JOURNALNODE:
          dfs_journalnode_edits_dir: /dfs/jn
        SECONDARYNAMENODE:
          fs_checkpoint_dir_list: /dfs/snn
      OZONE:
        SERVICEWIDE:
          ozone.service.id: o3service1
          'ozone-conf/ozone-site.xml_service_safety_valve': >
            <property>
                    <name>ozone.administrators</name>
                    <value>cloudera-scm/admin@{{ krb5_realm }}</value>
            </property>
        OZONE_DATANODE:
          hdds.datanode.dir: /dfs/o3dn/data1,/dfs/o3dn/data2
      HIVE:
        HIVEMETASTORE:
          hive_enable_db_notification: true
          hive_metastore_delegation_token_store: org.apache.hadoop.hive.thrift.DBTokenStore
      YARN:
        RESOURCEMANAGER:
          yarn_scheduler_maximum_allocation_mb: 4096
          yarn_scheduler_maximum_allocation_vcores: 4
        NODEMANAGER:
          yarn_nodemanager_resource_memory_mb: 4096
          yarn_nodemanager_resource_cpu_vcores: 4
          yarn_nodemanager_local_dirs:  /tmp/nm
          yarn_nodemanager_log_dirs: /var/log/nm
        GATEWAY:
          mapred_submit_replication: 3
          mapred_reduce_tasks: 6
      ZOOKEEPER:
        SERVICEWIDE:
          zookeeper_datadir_autocreate: true
      KNOX:
        SERVICEWIDE:
          knox_encryptquerystring_secret: Secret123
          knox_hadoop_auth_config_signature_secret: Secret123
        KNOX_GATEWAY:
          gateway_knox_admin_groups: admin
          gateway_master_secret: Secret123
    host_templates:
      Master1:
        ATLAS: [ATLAS_SERVER]
        HBASE: [MASTER]
        HDFS: [NAMENODE, JOURNALNODE, FAILOVERCONTROLLER]
        HIVE: [HIVEMETASTORE]
        RANGER: [RANGER_ADMIN]
        INFRA_SOLR: [SOLR_SERVER]
        YARN: [RESOURCEMANAGER]
        ZOOKEEPER: [SERVER]
        OZONE: [OZONE_MANAGER,STORAGE_CONTAINER_MANAGER]
      Master2:
        HBASE: [MASTER]
        HDFS: [NAMENODE, JOURNALNODE, FAILOVERCONTROLLER]
        HIVE: [HIVEMETASTORE]
        QUEUEMANAGER: [QUEUEMANAGER_STORE, QUEUEMANAGER_WEBAPP]
        INFRA_SOLR: [SOLR_SERVER]
        YARN: [RESOURCEMANAGER]
        ZOOKEEPER: [SERVER]
        OZONE: [OZONE_MANAGER]
      Master3:
        HDFS: [JOURNALNODE, BALANCER]
        HBASE: [MASTER]
        RANGER: [RANGER_TAGSYNC, RANGER_USERSYNC]
        INFRA_SOLR: [SOLR_SERVER]
        YARN: [JOBHISTORY]
        ZOOKEEPER: [SERVER]
        OZONE: [OZONE_MANAGER,OZONE_PROMETHEUS,OZONE_RECON]
      Edge:
        HIVE: [GATEWAY]
        HIVE_ON_TEZ: [HIVESERVER2]
        HDFS: [GATEWAY]
        TEZ: [GATEWAY]
        OZONE: [GATEWAY,S3_GATEWAY]
        KNOX: ['KNOX_GATEWAY']
      Workers:
        HDFS: [DATANODE]
        YARN: [NODEMANAGER]
        OZONE: [OZONE_DATANODE]
        HBASE: [REGIONSERVER]
        KAFKA: [KAFKA_BROKER]

mgmt:
  name: Cloudera Management Service
  services: [ALERTPUBLISHER, EVENTSERVER, HOSTMONITOR, REPORTSMANAGER, SERVICEMONITOR]

hosts:
  configs:
    host_default_proc_memswap_thresholds:
      warning: never
      critical: never
    host_memswap_thresholds:
      warning: never
      critical: never
    host_config_suppression_agent_system_user_group_validator: true
